# see https://symfony.com/doc/current/reference/configuration/framework.html
# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 3600
        gc_maxlifetime: 3600
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
