vich_uploader:
    db_driver: orm

    mappings:
       user:
           uri_prefix: /uploads/user
           upload_destination: '%kernel.project_dir%/public/uploads/user'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       drivingLicense: 
           uri_prefix: /uploads/drivingLicense
           upload_destination: '%kernel.project_dir%/public/uploads/drivingLicense'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       registrationCertificate:  
           uri_prefix: /uploads/registrationCertificate
           upload_destination: '%kernel.project_dir%/public/uploads/registrationCertificate'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       vehiclePhoto:  
           uri_prefix: /uploads/vehiclePhoto
           upload_destination: '%kernel.project_dir%/public/uploads/vehiclePhoto'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

